# -*- coding: utf-8 -*-
"""CustomerCare.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q4zO5Xrwq2dcoPJvy2ShG39TTb_uFJkP
"""

class CustomerCareVerification:
    def __init__(self):
        self.verified_numbers = {
            "Kisan Call Centre": '18001801551',
            "IMD Weather on Web": '18001801717',
            "Crop Insurance Schemes - ICICI Lombard": '18002666',
            "Crop Insurance Schemes - IFFCO Tokio": '18001035499',
            "Crop Insurance Schemes - Reliance General": '18003009',
            "Crop Insurance Schemes - Royal Sundaram": '18604250000',
            "Crop Insurance Schemes - TATA AIG Insurance": '18002667780',
            "Crop Insurance Schemes - Future Generali": '1800220233',
            "Crop Insurance Schemes - HDFC ERGO": '18002700700',
            "Crop Insurance Schemes - Chola Insurance": '18002005544',
            "Crop Insurance Schemes - L&T Insurance": '18002095846',
            "Air Asia": '18605008000',
            "Air India": '18001801407',
            "Jet Airways": '1800225522',
            "Spice Jet": '18001803333',
            "Indian Railway Reservation (IRCTC)": '1800111139',
            "ABN AMRO": '1800112224',
            "Allahabad Bank ATM": '1800220363',
            "Axis Bank": '18604258888',
            "Canara Bank": '1800446000',
            "Citibank": '1800442265',
            "Corporation Bank": '1800443555',
            "Development Credit Bank": '1800225769',
            "HDFC Bank": '1800227227',
            "ICICI Bank": '1800333499',
            "ICICI Bank NRI": '1800224848',
            "IDBI Bank": '1800116999',
            "Indian Bank": '18004251400',
            "ING Vysya": '1800449900',
            "Kotak Mahindra Bank": '1800226022',
            "Lord Krishna Bank": '1800112300',
            "Punjab National Bank": '1800122222',
            "State Bank of India": '18002337933',
            "Syndicate Bank": '1800446655',
            "Central Board of Secondary Education (CBSE) - Helpline": '1800117002',
            "ICRI Global Research": '18001030006',
            "India Post Office - Speed Post Customer Care": '1800119888',
            "India Post Office - Logistics Post Service": '1800119888',
            "Central Building Research Institute (CBRI)": '18002700800',
            "Indian Renewable Energy Development Agency Limited (IREDA)": '1800111442',
            "Anti Ragging Helpline": '18001805522',
            "National Council of Educational Research and Training (NCERT)": '1800111265',
            "Central Board of Secondary Education (CBSE) - Helpline": '1800118002',
            "University Grant Commission - Helpline": '18001805522',
            "Kendriya Vidyalaya Sangathan (Delhi region-KVS)": '1800118002',
            "Navodaya Vidyalaya Samiti (NVS)": '18003450092',
            "The National Institute of Open Schooling (NIOS)": '18001809393',
            "National Commission for Minority Educational Institutions": '1800110088',
            "Virtual Call Centre of National Council for Teacher Education (NCTE)": '1800110039',
            "National Minorities Development & Finance Corporation": '14402',
            "LIC Housing Finance": '1800440005',
            "SBI Mutual Fund": '1800223040',
            "Credit Guarantee Trust": '1800222659',
            "Pradhan Mantri Awas Yojana (Gramin)": '1800-11-6446',
            "Helpline for Handloom Weavers ‘Bunkar Mitra’ - Working Hours: 10:00 AM to 6:00 PM": '18002089988',
            "Startup India Hub - Working Hours: 10:00 AM to 5:30 PM": '1800115565',
            "Help Centre on Gold Schemes of Government of India": '18001800000',
            "'Eyeway National Helpdesk' for Visually Impaired Citizens": '180030020469',
            "UIDAI - Aadhar Card": '18003001947',
            "Anti Corruption Bureau": '1800222021',
            "Delhi VAT Helpline": '1800110066',
            "Insurance Regulatory and Development Authority (IRDA)": '18004254372',
            "National Consumer Helpline": '1800114000',
            "Core Centre Helpline": '18001804566',
            "PF Office Mumbai": '1800118005',
            "Telecom Monitoring Cell": '1800110420',
            "Ex. Serviceman Contributory Health Scheme (ECHS) - Helpline": '1800114115',
            "Registrar General and Census Commissioner India": '1800 110 111',
            "Insurance Regulatory and Development Authority (IRDA)": '18004254372',
            "Tax Return Prepares (TRPS)": '18001023738',
            "Central Vigilance Commission": '1800 11 0180',
            "Income Tax-e-Filling": '1800 4250 0025',
            "e-procurement": '1800 3070 2232',
            "Income Tax Department": '18004252229',
            "Passport Seva Kendra": '18002581800',
            "PAN Card": '18001801961',
            "Telecom Monitoring Cell": '1800110420',
            "Registrar General and Census Commissioner, India": '1800110111',
            "TIN Verification Number": '18001801961',
            "Tax Return Prepares (TRPS)": '18001023738',
            "Mahatma Gandhi National Rural Employment Guarantee Act (NREGA)": '1800110707',
            "Jan Aushadhi": '18001808080',
            "Central Vigilance Commission": '1800110180',
            "Income Tax-e-Filling": '180042500025',
            "e-procurement": '180030702232',
            "Central Pension Accounting Open Pradhan Mantri Jan-Dhan Yojana": '1800117788',
            "Community Radio Facilitation Centre": '1800 11 6346',
            "National Career Service": '1800-425-1514 (Timing: Tue-Sun 08:00 AM to 08:00 PM)',
            "Toll Free Helpline for Cable TV Digitisation": '1-800-180-4343',
            "Pharma Jan Samadhan": '1800111255',
            "AIIMS": '1800 11 6117',
            "AIDS Help Line": '1800111097',
            "H1N1 FLU (Swine Flu) - Helpline": '1800 11 4377',
            "VIMHANS-Child Care": '1800 11 3444',
            "National AIDS Control Organisation (NACO)": '18004191800',
            "Reproductive health, Family planning and infant health": '1800116555',
            "Bharat Gas": '1800222725',
            "Hindustan Petroleum": '18002333777',
            "Indra Prastha Gas Ltd. (IGL)": '18601801817',
            "Indane Gas": '18002333555',
            "Mahanagar Gas": '1800229944'
        }


    def identify_number_owner(self, incoming_number):
        for company_name, verified_number in self.verified_numbers.items():
            if incoming_number == verified_number:
                return f"Safe Number. The incoming number '{incoming_number}' belongs to {company_name}."

        # If the incoming number is not found in the dictionary
        return f"Potential scam alert! Incoming number '{incoming_number}' is not recognized."

# Example1:
customer_care_verifier = CustomerCareVerification()
incoming_number_input = input("Enter the incoming number: ")
number_owner_info = customer_care_verifier.identify_number_owner(incoming_number_input)
print(number_owner_info)

# Example2:
customer_care_verifier = CustomerCareVerification()
incoming_number_input = input("Enter the incoming number: ")
number_owner_info = customer_care_verifier.identify_number_owner(incoming_number_input)
print(number_owner_info)