# -*- coding: utf-8 -*-
"""FakeAdvertisement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nxiF-m5o0LyQBPX6eWBH3ST03Y-o9EUk
"""

# Install Tesseract OCR
!sudo apt install tesseract-ocr

# Install Python libraries
!pip install pytesseract opencv-python pillow pyenchant requests beautifulsoup4 textblob

!pip install language_tool_python

# Import necessary libraries
import cv2
import pytesseract
from PIL import Image
import requests
from bs4 import BeautifulSoup
from textblob import TextBlob
import language_tool_python

# Update pytesseract configuration for Google Colab
pytesseract.pytesseract.tesseract_cmd = '/usr/bin/tesseract'

# Function to check for grammatical errors in text using LanguageTool
def check_grammar(text):
    tool = language_tool_python.LanguageTool('en-US')
    matches = tool.check(text)
    return [match.ruleIssueType.lower() for match in matches]

# Function to check sentiment of the text using TextBlob
def check_sentiment(text):
    blob = TextBlob(text)
    sentiment_score = blob.sentiment.polarity
    return sentiment_score

# Function to extract text from image using pytesseract
def extract_text_from_image(image_path):
    img = cv2.imread(image_path)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    text = pytesseract.image_to_string(gray)
    return text

# Function to check if a webpage exists
def check_webpage(url):
    try:
        response = requests.get(url)
        return response.status_code == 200
    except:
        return False

def analyze_screenshot(image_path, ad_url):
    # Extract text from the image
    text = extract_text_from_image(image_path)

    # Check for grammatical errors
    grammar_errors = check_grammar(text)

    # Check sentiment of the text
    sentiment_score = check_sentiment(text)

    # Check if the webpage exists
    webpage_exists = check_webpage(ad_url)

    # Analyze results
    if len(grammar_errors) > 0 or sentiment_score < 0 or not webpage_exists:
        print("Fraudulent ad detected!")
        print("Grammatical Errors:", grammar_errors)
        print("Sentiment Score:", sentiment_score)
        print("Webpage Exists:", webpage_exists)
    else:
        print("Ad is likely legitimate.")

# Example usage
image_path = "/content/sample_data/real_macd.jpg"
ad_url = "https://www.mcdods.com/us/en-us.html"
analyze_screenshot(image_path, ad_url)

